// BBL Pitcher Report Data — extracted from v4 통합 리포트 DOCX files
// Display order: 홍주환 → 정원진 → 김주원 → 권준서
window.BBL_PITCHERS = [
  {
    id: 'hong',
    name: '홍주환',
    nameEn: 'Hong Ju-hwan',
    video: 'assets/hong.mp4',
    velocity: 137.9,
    velocityAvg: 135.0,
    archetype: '하체 파워 주도형',
    archetypeEn: 'Power-dominant (mid strength)',
    tags: ['reactive+'],
    coreIssue: '모든 구간 기준 충족 · 뚜렷한 약점 없음',
    coreIssueEn: 'No bottleneck — maintain current balance',
    severity: 'NONE',
    date: '2026-04-24',
    physical: {
      weightKg: 75.0,
      heightCm: 170,
      cmjPower: { cmj: 56.9, sj: 47.0, cmjAbs: 4268, sjAbs: 3525, band: 'high' },
      maxStrength: { abs: 2092, perKg: 27.9, band: 'mid' },
      reactive: { cmj: 0.67, sj: 0.99, band: 'high' },
      ssc: { value: 1.08, band: 'mid' },
      release: { value: 54.7, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 56.9, display: '56.9',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 47.0, display: '47.0',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: 27.9, display: '27.9',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.67, display: '0.67',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.08, display: '1.08',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 54.7, display: '54.7',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 41, armMs: 92,
      g1: 41, g2: 51,
      comment: '· P→T lag 41ms (SD ±5.2) · T→A lag 51ms (SD ±4.4) · 모두 정상 · 일관성 우수',
    },
    angular: {
      pelvis: 635, trunk: 843, arm: 1578,
      pelvisBand: 'mid', trunkBand: 'mid', armBand: 'mid',
      gainPT: 1.33, gainTA: 1.87,
      comment: '· 3개 분절 모두 4인 중 1-2위 · pelvis 635 → trunk 843 → arm 1578°/s · 매끄러운 가속 + 큰 절대값',
    },
    energy: {
      etiPT: 1.33, etiTA: 1.87, leakPct: 0,
      comment: '· ETI T→A 1.87 (4명 중 1위) · 누수 0% · 분절 lag P→T 41ms, T→A 51ms 모두 정상 · fc→release 482ms 일관성 압도적 (CV 1.3%)',
    },
    command: {
      strikePct: 61.7, plateSdCm: 21.0, grade: 'B',
      breakdown: { wrist: -1.8, armslot: -2.8, trunkTilt: -2.4, layback: -2.5, stride: -2.3, fcRelease: -0.7 },
      measured: {
        wristHeightSdCm: 1.75,
        armSlotSdDeg: 3.48,
        trunkTiltSdDeg: 1.98,
        laybackCvPct: 6.32,
        strideCvPct: 1.55,
        fcReleaseMs: 482,
        fcReleaseCvPct: 1.3,
      },
      note: '· 7대 요인 종합: B/A/B/B/A/D/B · 5개 요인 정상 · ⑥ 머리 안정성 D등급(개선 필요)',
      isDemo: false,
      nTrials: 10,
    },
    factors: [
      { id: 'F1_landing', name: '① 앞발 착지', grade: 'B', measured: { stride_m: 0.99, stride_cv: 1.5, knee_flex_deg: 53.0, knee_sd: 7.0 }, elite: 'stride CV 2-3% · knee 25-40° · SD 3-5°', comment: '· stride 0.99m · CV 1.5% · knee@FC 53° (엘리트 25-40°) · SD ±7.0° (엘리트 3-5°)' },
      { id: 'F2_separation', name: '② 골반-몸통 분리', grade: 'A', measured: { max_sep_deg: 28.0, sep_sd: 2.2, sep_lag_ms: 41.0, lag_sd: 5.2 }, elite: '40-60° · lag ~50ms · SD <10ms', comment: '· max separation 28° (엘리트 40-60° · 평균 미달) · separation lag 41ms (엘리트 ~50ms) · SD ±5.2ms' },
      { id: 'F3_arm_timing', name: '③ 어깨-팔 타이밍', grade: 'B', measured: { mer_deg: 187.1, mer_sd: 2.6, fc_to_br_ms: 77.0, fcbr_sd: 21.0 }, elite: 'MER ~180° · FC→BR ~150ms · SD <10ms', comment: '· MER 194° (엘리트 ~180°) · SD ±12.3° · FC→BR 77ms · SD ±21ms' },
      { id: 'F4_knee', name: '④ 앞 무릎 안정성', grade: 'B', measured: { knee_fc_deg: 53.0, knee_sd: 7.0, blocking_deg: -17.0, block_sd: 9.1 }, elite: '25-40° · blocking + (펴짐) · SD <5°', comment: '· knee@FC 53° · SD ±7.0° · blocking -17° 굽힘 (no blocking)' },
      { id: 'F5_tilt', name: '⑤ 몸통 기울기', grade: 'A', measured: { forward_deg: 37.0, forward_sd: 2.0, lateral_deg: 19.0, lateral_sd: 1.3 }, elite: 'forward 30-40° · lateral 20-30° · SD 3-5°', comment: '· forward 37° (엘리트 30-40°) SD ±2.0° · lateral 19° (엘리트 20-30°) SD ±1.3°' },
      { id: 'F6_head', name: '⑥ 머리·시선 안정성', grade: 'D', measured: { head_disp_cm: 32.0, head_sd: 7.33 }, elite: '5-10cm · SD 1-2cm', comment: '· head displacement (FC→BR) 32cm · SD ±7.33cm (엘리트 1-2cm)' },
      { id: 'F7_wrist', name: '⑦ 그립·손목 정렬', grade: 'B', measured: { arm_slot_deg: 42.0, arm_sd: 3.48 }, elite: 'arm_slot SD <3°', comment: '· arm_slot 42° · SD ±3.48° (엘리트 2-3°)' }
    ],
    layback: { deg: 187.1, band: 'high', note: '· 187.1° · 4명 중 가장 큰 layback · 가속 거리 충분 · SD ±2.6°' },
    strengths: [
      { title: '하체 단위파워 우수', detail: '· CMJ 단위파워 56.9 W/kg · 기준 상위' },
      { title: '반응·폭발성 (RSI) 우수', detail: '· CMJ RSI-mod 0.67 m/s · 기준 상위' },
      { title: '몸통→상완 에너지 전달 우수', detail: '· ETI 1.04 · 기준 상위' },
    ],
    weaknesses: [
      { title: '전 영역 기준 충족 · 약점 없음', detail: '· 현재 수준을 유지하며 절대 근력 보강 시 추가 상승 여력' },
    ],
    flags: [],
    training: [
      { cat: '근력', title: '근력 보강 (단위파워 유지)', weeks: '6–8주',
        rationale: '· 단위파워 이미 우수 · 절대 근력 증가 시 파워 총량 동반 상승 · 혼자서도 덤벨·자중 기반으로 진행 가능',
        drills: [
          '고블릿 스쿼트 (덤벨 1개) 4세트 × 6–8회 · 주 2회',
          '싱글 레그 루마니안 데드리프트 (덤벨) 3세트 × 8회 · 엉덩이-햄스트링 타깃',
          '스텝업 (의자·벤치) 3세트 × 10회 · 좌우 교대',
          '푸시업 변형 (일반·다이아몬드·디클라인) 4세트 × 15회',
          '셀프 체크: 각 세트 후 스마트폰 영상으로 자세 확인 · 무릎 안쪽 무너짐/허리 둥글림 없는지',
        ] },
    ],
  },
  {
    id: 'jeong',
    name: '정원진',
    nameEn: 'Jeong Won-jin',
    video: 'assets/jeong.mp4',
    velocity: 133.0,
    velocityAvg: 131.2,
    archetype: '파워 개발 필요형',
    archetypeEn: 'Power-deficit (strength untested)',
    tags: ['reactive-'],
    coreIssue: '몸통→상완 에너지 누수',
    coreIssueEn: 'Trunk → Arm energy transfer inefficiency',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      weightKg: 79.0,
      heightCm: 181,
      cmjPower: { cmj: 48.3, sj: 29.1, cmjAbs: 3816, sjAbs: 2299, band: 'low' },
      maxStrength: { abs: null, perKg: null, band: 'na' },
      reactive: { cmj: 0.49, sj: 0.27, band: 'low' },
      ssc: { value: 1.09, band: 'mid' },
      release: { value: 50.0, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 48.3, display: '48.3',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 29.1, display: '29.1',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: null, display: 'N/A',   lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.27, display: '0.27',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.09, display: '1.09',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 50.0, display: '50.0',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 42, armMs: 80,
      g1: 42, g2: 38,
      comment: '· P→T lag 42ms 다소 김 · T→A lag 38ms 짧음 (정상 50ms 미달) · 그러나 SD ±7.1로 매우 일관',
    },
    angular: {
      pelvis: 612, trunk: 836, arm: 1475,
      pelvisBand: 'mid', trunkBand: 'mid', armBand: 'mid',
      gainPT: 1.37, gainTA: 1.77,
      comment: '· pelvis·trunk·arm 모두 정상 범위 · arm peak 1475°/s · 균형 잡힌 회전 속도 · 일관성 매우 우수 (모든 분절 SD 4인 중 최소)',
    },
    energy: {
      etiPT: 1.37, etiTA: 1.77, leakPct: 0,
      comment: '· ETI T→A 1.77 · 누수 0% · P→T lag 42ms 다소 김 · T→A lag 38ms 짧음 · 어깨 외회전 형성 시간 부족 (layback 131° 평균 미달의 직접 원인)',
    },
    command: {
      strikePct: 75.0, plateSdCm: 14.8, grade: 'A',
      breakdown: { wrist: -1.6, armslot: -1.2, trunkTilt: -1.2, layback: -0.5, stride: -1.5, fcRelease: -1.4 },
      measured: {
        wristHeightSdCm: 1.55,
        armSlotSdDeg: 1.44,
        trunkTiltSdDeg: 0.96,
        laybackCvPct: 1.2,
        strideCvPct: 1.0,
        fcReleaseMs: 480,
        fcReleaseCvPct: 2.8,
      },
      note: '· 7대 요인 종합: A/A/A/A/A/A/A · 메카닉 일관성 4명 중 압도적 1위 · 모든 요인 A 또는 양호',
      isDemo: false,
      nTrials: 10,
    },
    factors: [
      { id: 'F1_landing', name: '① 앞발 착지', grade: 'A', measured: { stride_m: 1.0, stride_cv: 1.0, knee_flex_deg: 50.0, knee_sd: 3.0 }, elite: 'stride CV 2-3% · knee 25-40° · SD 3-5°', comment: '· stride 1.00m · CV 1.0% · knee@FC 50° (엘리트 25-40°) · SD ±3.0° (엘리트 3-5°)' },
      { id: 'F2_separation', name: '② 골반-몸통 분리', grade: 'A', measured: { max_sep_deg: 27.0, sep_sd: 1.3, sep_lag_ms: 42.0, lag_sd: 2.4 }, elite: '40-60° · lag ~50ms · SD <10ms', comment: '· max separation 27° (엘리트 40-60° · 평균 미달) · separation lag 42ms (엘리트 ~50ms) · SD ±2.4ms' },
      { id: 'F3_arm_timing', name: '③ 어깨-팔 타이밍', grade: 'A', measured: { mer_deg: 169.2, mer_sd: 4.2, fc_to_br_ms: 46.0, fcbr_sd: 0.0 }, elite: 'MER ~180° · FC→BR ~150ms · SD <10ms', comment: '· MER 132° (엘리트 ~180°) · SD ±1.6° · FC→BR 46ms · SD ±0ms' },
      { id: 'F4_knee', name: '④ 앞 무릎 안정성', grade: 'A', measured: { knee_fc_deg: 50.0, knee_sd: 3.0, blocking_deg: -2.0, block_sd: 1.9 }, elite: '25-40° · blocking + (펴짐) · SD <5°', comment: '· knee@FC 50° · SD ±3.0° · blocking -2° 굽힘 (no blocking)' },
      { id: 'F5_tilt', name: '⑤ 몸통 기울기', grade: 'A', measured: { forward_deg: 26.0, forward_sd: 1.0, lateral_deg: 9.0, lateral_sd: 0.7 }, elite: 'forward 30-40° · lateral 20-30° · SD 3-5°', comment: '· forward 26° (엘리트 30-40°) SD ±1.0° · lateral 9° (엘리트 20-30°) SD ±0.7°' },
      { id: 'F6_head', name: '⑥ 머리·시선 안정성', grade: 'A', measured: { head_disp_cm: 19.0, head_sd: 0.55 }, elite: '5-10cm · SD 1-2cm', comment: '· head displacement (FC→BR) 19cm · SD ±0.55cm (엘리트 1-2cm)' },
      { id: 'F7_wrist', name: '⑦ 그립·손목 정렬', grade: 'A', measured: { arm_slot_deg: 51.0, arm_sd: 1.44 }, elite: 'arm_slot SD <3°', comment: '· arm_slot 51° · SD ±1.44° (엘리트 2-3°)' }
    ],
    layback: { deg: 169.2, band: 'mid', note: '· 169.2° · 정상 범위 · SD ±4.2° (4인 중 안정성 1위급)' },
    strengths: [
      { title: '신장성 활용 (SSC) 정상', detail: '· EUR 1.09 · SSC 활용 정상 범위' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.77 · 기준 0.85 미만' },
      { title: '하체 단위파워 기준 미만', detail: '· SJ 단위파워 29.1 W/kg' },
      { title: '반응·폭발성 (RSI) 기준 미만', detail: '· SJ RSI-mod 0.27 m/s' },
    ],
    flags: [
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.77 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 확보 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선 (셀프)', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 몸통 운동량 상완 전달 부족 · 혼자 매일 10분 루틴',
        drills: [
          'Connection ball 드릴 대체: 수건 두 개를 말아 겨드랑이에 끼우고 쉐도우 투구 30회 · 팔-몸통 분리감',
          'Lag 드릴: 수건 잡고 투구 동작 20회 · 수건이 늦게 따라오는 감각',
          '흉추 회전 모빌리티: Open Book 자세 좌우 10회 × 2세트 · 바닥에서 혼자',
          '거울 쉐도우: 거울 앞 투구 동작 15회 · 팔이 몸통보다 먼저 돌지 않는지 확인',
          '셀프 체크: 측면 셀카 영상으로 골반-어깨 분리각 30–45° 유지 여부',
        ] },
      { cat: '파워', title: '하체 파워 개발 (자중·점프)', weeks: '6–8주',
        rationale: '· 하체 단위파워 기준 미만 · 장비 없이 운동장/집에서 가능한 점프·플라이오 위주',
        drills: [
          '박스 점프 (계단·튼튼한 벤치 30–40cm) 3세트 × 5회 · 주 2회 · 충분한 휴식',
          '브로드 점프 (제자리멀리뛰기) 3세트 × 5회 · 착지 안정 우선',
          '점프 스쿼트 (자중) 4세트 × 6회 · 폭발적 상승',
          '측방 바운드 (좌우 점프) 3세트 × 8회 · 투구 하체 힘 방향 특화',
          '셀프 체크: 거리/높이를 매주 기록 · 10% 이내 편차면 일관성 OK',
        ] },
    ],
  },
  {
    id: 'kim',
    name: '김주원',
    nameEn: 'Kim Ju-won',
    video: 'assets/kim.mp4',
    velocity: 145.1,
    velocityAvg: 140.9,
    archetype: '재능형 · 능력 외 투구',
    archetypeEn: 'Skill-Outperforming · Talent-Driven',
    tags: ['skill-outperforming', 'injury-risk-high', 'high-upside'],
    coreIssue: '측정 데이터 대비 +13 km/h · 재능 위에 던지는 케이스 · 부상 위험 ↑ 보강 시 잠재력 큼',
    coreIssueEn: 'Throwing above measured capacity · injury risk + huge upside',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      weightKg: 85.0,
      heightCm: null,
      cmjPower: { cmj: 37.7, sj: 43.7, cmjAbs: 3205, sjAbs: 3715, band: 'low' },
      maxStrength: { abs: 2525, perKg: 29.7, band: 'mid' },
      reactive: { cmj: 0.46, sj: 0.62, band: 'high' },
      ssc: { value: 1.18, band: 'high' },
      release: { value: 74.2, band: 'high' },
    },
    radar: [
      // axis, label, sub, value, low, high, displayValue
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 37.7, display: '37.7',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 43.7, display: '43.7',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: 29.7, display: '29.7',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.46, display: '0.46',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.18, display: '1.18',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 74.2, display: '74.2',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 51, armMs: 110,
      g1: 51, g2: 59,
      comment: '· P→T lag 51ms (SD ±7.1) · T→A lag 59ms · 시퀀스 자체는 교과서적 · 그러나 fc→release CV 20.9%로 timing 일관성 부족',
    },
    angular: {
      pelvis: 569, trunk: 682, arm: 1383,
      pelvisBand: 'mid', trunkBand: 'low', armBand: 'low',
      gainPT: 1.2, gainTA: 2.03,
      comment: '· pelvis 569, trunk 682°/s 모두 4인 중 가장 낮음 · 그러나 arm 1383°/s 도달 · ETI T→A 2.03로 압도적 1위 · "약한 분절을 효율로 보상"하는 능력 외 투구 메커니즘',
    },
    energy: {
      etiPT: 1.2, etiTA: 2.03, leakPct: 0,
      comment: '· ETI T→A 2.03 4명 중 압도적 1위 · 누수 0% · 약한 분절 회전을 ETI 효율로 완전히 보상 · 그러나 fc→release CV 20.9% (시행마다 timing 다름) → "재능형"의 위험 신호',
    },
    command: {
      strikePct: 66.4, plateSdCm: 18.8, grade: 'A',
      breakdown: { wrist: -2.5, armslot: -2.8, trunkTilt: -1.2, layback: -0.6, stride: -1.0, fcRelease: -10.4 },
      measured: {
        wristHeightSdCm: null,
        armSlotSdDeg: null,
        trunkTiltSdDeg: 0.97,
        laybackCvPct: 1.62,
        strideCvPct: 0.65,
        fcReleaseMs: 650,
        fcReleaseCvPct: 20.9,
      },
      note: '· 7대 요인 종합: A/A/A/B/A/C/na · 측정 가능 변수 모두 우수 · ⑥ 머리 안정성만 보강 필요',
      isDemo: false,
      nTrials: 10,
    },
    factors: [
      { id: 'F1_landing', name: '① 앞발 착지', grade: 'A', measured: { stride_m: 1.09, stride_cv: 0.7, knee_flex_deg: 47.0, knee_sd: 3.3 }, elite: 'stride CV 2-3% · knee 25-40° · SD 3-5°', comment: '· stride 1.09m · CV 0.7% · knee@FC 47° (엘리트 25-40°) · SD ±3.3° (엘리트 3-5°)' },
      { id: 'F2_separation', name: '② 골반-몸통 분리', grade: 'A', measured: { max_sep_deg: 30.0, sep_sd: 2.4, sep_lag_ms: 51.0, lag_sd: 7.1 }, elite: '40-60° · lag ~50ms · SD <10ms', comment: '· max separation 30° (엘리트 40-60° · 평균 미달) · separation lag 51ms (엘리트 ~50ms) · SD ±7.1ms' },
      { id: 'F3_arm_timing', name: '③ 어깨-팔 타이밍', grade: 'A', measured: { mer_deg: 196.6, mer_sd: 6.4, fc_to_br_ms: 89.0, fcbr_sd: 10.0 }, elite: 'MER ~180° · FC→BR ~150ms · SD <10ms', comment: '· MER 140° (엘리트 ~180°) · SD ±2.3° · FC→BR 89ms · SD ±10ms' },
      { id: 'F4_knee', name: '④ 앞 무릎 안정성', grade: 'B', measured: { knee_fc_deg: 47.0, knee_sd: 3.3, blocking_deg: -9.0, block_sd: 7.5 }, elite: '25-40° · blocking + (펴짐) · SD <5°', comment: '· knee@FC 47° · SD ±3.3° · blocking -9° 굽힘 (no blocking)' },
      { id: 'F5_tilt', name: '⑤ 몸통 기울기', grade: 'A', measured: { forward_deg: 37.0, forward_sd: 1.0, lateral_deg: 23.0, lateral_sd: 1.2 }, elite: 'forward 30-40° · lateral 20-30° · SD 3-5°', comment: '· forward 37° (엘리트 30-40°) SD ±1.0° · lateral 23° (엘리트 20-30°) SD ±1.2°' },
      { id: 'F6_head', name: '⑥ 머리·시선 안정성', grade: 'C', measured: { head_disp_cm: 50.0, head_sd: 5.39 }, elite: '5-10cm · SD 1-2cm', comment: '· head displacement (FC→BR) 50cm · SD ±5.39cm (엘리트 1-2cm)' },
      { id: 'F7_wrist', name: '⑦ 그립·손목 정렬', grade: 'na', measured: {  }, elite: 'arm_slot SD <3°', comment: '· wrist height 측정 실패 · 마커리스 모션캡처 한계' }
    ],
    layback: { deg: 196.6, band: 'high', note: '· 196.6° · 4인 중 가장 큰 layback · 가속 거리 우수 · SD ±6.4°' },
    strengths: [
      { title: '반응·폭발성 (RSI) 우수', detail: '· SJ RSI-mod 0.62 m/s · 기준 상위' },
      { title: '신장성 활용 (SSC) 우수', detail: '· EUR 1.18 · SSC 활용 강함 · CMJ·SJ 격차 큼' },
      { title: '악력 우수', detail: '· 악력 74.2 kg · 기준 상위 · 전완·손목 용량 충분' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.68 · 기준 0.85 미만' },
      { title: '하체 단위파워 기준 미만', detail: '· CMJ 단위파워 37.7 W/kg' },
    ],
    flags: [
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.68 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 확보 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선 (셀프)', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 분절 타이밍·흉추 가동성 핵심 축 · 매일 10분 혼자 수행',
        drills: [
          '수건 말아 겨드랑이 끼기 + 쉐도우 투구 30회 · 팔-몸통 분리 감각 형성',
          'Lag 드릴: 수건 끝 잡고 투구 20회 · 수건이 늦게 따라오는 느낌',
          'Open Book 흉추 모빌리티: 옆으로 누워 팔 여닫기 좌우 각 10회 × 2세트',
          '폼롤러 흉추 신전: 10회 × 2세트 (폼롤러 없으면 수건 말아서 대체)',
          '셀프 체크: 측면 셀카로 골반-어깨 분리각 유지(30–45°, 0.05초 이상) 확인',
        ] },
      { cat: '파워', title: '파워 변환 (점프·플라이오 중심)', weeks: '6–8주',
        rationale: '· 절대 근력 양호 · 폭발적 발현력 부족 · 혼자서 가능한 점프·탄성 드릴로 RSI 개선',
        drills: [
          '뎁스 점프 (낮은 계단 30cm) 3세트 × 5회 · 땅 닿자마자 바로 점프',
          '회전 메디볼 던지기 (3–5kg) 좌우 각 4세트 × 6회 · 벽 대고 가능',
          '스플릿 점프 스쿼트 (자중·덤벨 선택) 3세트 × 6회 좌우 · 파워 변환 훈련',
          '브로드 점프 3세트 × 5회 · 매주 거리 기록',
          '셀프 체크: 점프 높이/거리가 4주 내 5–10% 증가하면 파워 변환 진행 중',
        ] },
    ],
  },
  {
    id: 'kwon',
    name: '권준서',
    nameEn: 'Kwon Jun-seo',
    video: 'assets/kwon.mp4',
    velocity: 122.7,
    velocityAvg: 121.1,
    archetype: '탄력 중심형',
    archetypeEn: 'Lightweight / Elastic',
    tags: ['reactive+'],
    coreIssue: '· 엔진 총량 부족 · 몸통→상완 전달 저하',
    coreIssueEn: 'Low engine size + Trunk → Arm inefficiency',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      weightKg: 65.4,
      heightCm: 181,
      cmjPower: { cmj: 56.7, sj: 57.5, cmjAbs: 3708, sjAbs: 3762, band: 'high' },
      maxStrength: { abs: 1765, perKg: 27.0, band: 'mid' },
      reactive: { cmj: 0.48, sj: 0.97, band: 'high' },
      ssc: { value: 1.10, band: 'mid' },
      release: { value: 49.1, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: '폭발력',     sub: '하체 폭발력',    value: 56.7, display: '56.7',  lo: 40, hi: 50 },
      { key: 'sj',    label: '순수파워',   sub: '정지→폭발',    value: 57.5, display: '57.5',  lo: 38, hi: 50 },
      { key: 'str',   label: '버티는 힘',  sub: '최대 근력',    value: 27.0, display: '27.0',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '빠른 반동',  sub: '순간 반응', value: 0.97, display: '0.97',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: '반동 활용',  sub: '탄성 에너지',     value: 1.10, display: '1.10',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '손목 힘',    sub: '릴리스 안정',      value: 49.1, display: '49.1',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 31, armMs: 105,
      g1: 31, g2: 74,
      comment: '· P→T lag 31ms · T→A lag 74ms (SD ±64.6, CV 87.4%) · 4명 중 timing 일관성 압도적으로 약함',
    },
    angular: {
      pelvis: 535, trunk: 917, arm: 1475,
      pelvisBand: 'low', trunkBand: 'mid', armBand: 'mid',
      gainPT: 1.72, gainTA: 1.61,
      comment: '· pelvis 535°/s 가장 낮음 · 그러나 trunk 917°/s 4명 중 1위 · P→T gain 1.72로 1위 · 그러나 T→A 가속에서 한계 (ETI 1.61 4인 중 가장 작음)',
    },
    energy: {
      etiPT: 1.72, etiTA: 1.61, leakPct: 0,
      comment: '· ETI T→A 1.61 4명 중 가장 작음 · 누수 0% · trunk peak 매우 빠르나(917°/s) arm 가속 못 따라감 · T→A lag CV 87.4% (4인 중 가장 변동) · fc→release 272ms로 너무 짧음 (다른 3명 480ms 대비 절반)',
    },
    command: {
      strikePct: 57.9, plateSdCm: 22.8, grade: 'B',
      breakdown: { wrist: -3.9, armslot: -3.0, trunkTilt: -3.5, layback: -10.0, stride: -4.7, fcRelease: -16.9 },
      measured: {
        wristHeightSdCm: 3.88,
        armSlotSdDeg: 3.78,
        trunkTiltSdDeg: 2.9,
        laybackCvPct: 25.05,
        strideCvPct: 3.15,
        fcReleaseMs: 272,
        fcReleaseCvPct: 33.9,
      },
      note: '· 7대 요인 종합: B/A/B/D/A/D/B · ④ 무릎과 ⑥ 머리 D등급 · 메카닉 일관성 회복이 최우선 과제',
      isDemo: false,
      nTrials: 10,
    },
    factors: [
      { id: 'F1_landing', name: '① 앞발 착지', grade: 'B', measured: { stride_m: 1.0, stride_cv: 3.1, knee_flex_deg: 35.0, knee_sd: 8.0 }, elite: 'stride CV 2-3% · knee 25-40° · SD 3-5°', comment: '· stride 1.00m · CV 3.1% · knee@FC 35° (엘리트 25-40°) · SD ±8.0° (엘리트 3-5°)' },
      { id: 'F2_separation', name: '② 골반-몸통 분리', grade: 'A', measured: { max_sep_deg: 37.0, sep_sd: 2.1, sep_lag_ms: 31.0, lag_sd: 9.9 }, elite: '40-60° · lag ~50ms · SD <10ms', comment: '· max separation 37° (엘리트 40-60° · 평균 미달) · separation lag 31ms (엘리트 ~50ms) · SD ±9.9ms' },
      { id: 'F3_arm_timing', name: '③ 어깨-팔 타이밍', grade: 'B', measured: { mer_deg: 186.4, mer_sd: 3.7, fc_to_br_ms: 111.0, fcbr_sd: 68.0 }, elite: 'MER ~180° · FC→BR ~150ms · SD <10ms', comment: '· MER 159° (엘리트 ~180°) · SD ±39.8° · FC→BR 111ms · SD ±68ms' },
      { id: 'F4_knee', name: '④ 앞 무릎 안정성', grade: 'D', measured: { knee_fc_deg: 35.0, knee_sd: 8.0, blocking_deg: -8.0, block_sd: 17.4 }, elite: '25-40° · blocking + (펴짐) · SD <5°', comment: '· knee@FC 35° · SD ±8.0° · blocking -8° 굽힘 (no blocking)' },
      { id: 'F5_tilt', name: '⑤ 몸통 기울기', grade: 'A', measured: { forward_deg: 38.0, forward_sd: 2.9, lateral_deg: 9.0, lateral_sd: 1.7 }, elite: 'forward 30-40° · lateral 20-30° · SD 3-5°', comment: '· forward 38° (엘리트 30-40°) SD ±2.9° · lateral 9° (엘리트 20-30°) SD ±1.7°' },
      { id: 'F6_head', name: '⑥ 머리·시선 안정성', grade: 'D', measured: { head_disp_cm: 48.0, head_sd: 18.2 }, elite: '5-10cm · SD 1-2cm', comment: '· head displacement (FC→BR) 48cm · SD ±18.20cm (엘리트 1-2cm)' },
      { id: 'F7_wrist', name: '⑦ 그립·손목 정렬', grade: 'B', measured: { arm_slot_deg: 54.0, arm_sd: 3.78 }, elite: 'arm_slot SD <3°', comment: '· arm_slot 54° · SD ±3.78° (엘리트 2-3°)' }
    ],
    layback: { deg: 186.4, band: 'high', note: '· 186.4° · 정상 범위 · 그러나 release 시점 ER만 154°로 떨어짐 · timing 불안정' },
    strengths: [
      { title: '하체 단위파워 우수', detail: '· CMJ 단위파워 56.7 W/kg · 기준 상위' },
      { title: '반응·폭발성 (RSI) 우수', detail: '· SJ RSI-mod 0.97 m/s · 기준 상위' },
      { title: '어깨 외회전 가동범위 우수', detail: '· Max Layback 186° · 기준 상위' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.60 · 기준 0.85 미만' },
      { title: '엔진 총량 부족', detail: '· 단위파워 양호 · 절대 용량 작음 (1765 N / 65.4 kg)' },
    ],
    flags: [
      { severity: 'MEDIUM', title: '엔진 총량 부족 · 단위파워 양호 · 절대 용량 작음',
        evidence: ['절대 근력 추정치 1765 N (IMTP_F) · Low 범위', '체중 65.4 kg', 'CMJ 단위파워 56.7 W/kg · High'],
        implication: '· 탄력·반응성 양호 · 근력·체중 총량 작음 · 구속 천장 제한 · 중량 복합운동 중심 절대 근력·체중 증가 블록 우선' },
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.60 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선 (셀프)', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 몸통 운동량 상완 전달 부족 · 매일 10분 루틴',
        drills: [
          '수건 겨드랑이 끼기 + 쉐도우 투구 30회 · 팔-몸통 연결 감각',
          'Lag 드릴: 수건 휘두르기 20회 · 팔 지연 타이밍',
          'Open Book 흉추 회전 좌우 각 10회 × 2세트',
          '폼롤러 흉추 신전 10회 × 2세트 · 폼롤러 없으면 타월 말아 사용',
          '셀프 체크: 측면 영상으로 분절 타이밍(골반→몸통→팔 순서) 확인',
        ] },
      { cat: '근력', title: '근력·체중 증가 블록 (홈·자중 중심)', weeks: '8–12주',
        rationale: '· 단위체중 파워 양호 · 절대 근력/체중 작음 · 혼자서 식단과 자중·덤벨 훈련 병행',
        drills: [
          '고블릿 스쿼트 (덤벨·배낭에 짐 넣어 대체 가능) 4세트 × 8–10회 · 주 2회',
          '불가리안 스플릿 스쿼트 3세트 × 8회 좌우 · 하체 근비대',
          '푸시업 (가중 옵션: 배낭) 4세트 × 최대 반복',
          '풀업/로우: 철봉 풀업 or 수건 후면 당김 (철봉 없으면 인버티드 로우)',
          '식단: 하루 단백질 체중 1kg당 1.6–2.0g · 0.25–0.5 kg/주 체중 증가 목표',
          '셀프 체크: 매주 같은 요일·시간 체중 측정 · 사진 기록(정면·측면)',
        ] },
    ],
  },
];

// Professional reference ranges
window.BBL_REF = {
  pelvis:  { low: 580, high: 640 },
  trunk:   { low: 800, high: 900 },
  arm:     { low: 1450, high: 1600 },
  layback: { low: 160, high: 180 },
  etiTA:   { leakBelow: 0.85, ideal: 1.0 },
};
