// BBL Pitcher Report Data — extracted from v4 통합 리포트 DOCX files
// Display order: 홍주환 → 정원진 → 김주원 → 권준서
window.BBL_PITCHERS = [
  {
    id: 'hong',
    name: '홍주환',
    nameEn: 'Hong Ju-hwan',
    video: 'assets/hong.mp4',
    velocity: 137.9,
    velocityAvg: 135.0,
    archetype: '하체 파워 주도형',
    archetypeEn: 'Power-dominant (mid strength)',
    tags: ['reactive+'],
    coreIssue: '모든 구간 기준 충족 · 뚜렷한 약점 없음',
    coreIssueEn: 'No bottleneck — maintain current balance',
    severity: 'NONE',
    date: '2026-04-24',
    physical: {
      cmjPower: { cmj: 56.9, sj: 47.0, band: 'high' },
      maxStrength: { abs: 1915, perKg: 27.9, band: 'mid' },
      reactive: { cmj: 0.67, sj: 0.99, band: 'high' },
      ssc: { value: 1.08, band: 'mid' },
      release: { value: 54.7, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: 'CMJ 파워',   sub: 'W/kg',    value: 56.9, display: '56.9',  lo: 40, hi: 50 },
      { key: 'sj',    label: 'SJ 파워',    sub: 'W/kg',    value: 47.0, display: '47.0',  lo: 38, hi: 50 },
      { key: 'str',   label: '절대근력',   sub: 'N/kg',    value: 27.9, display: '27.9',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '반응성',     sub: 'RSI-mod', value: 0.67, display: '0.67',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: 'EUR',        sub: 'SSC',     value: 1.08, display: '1.08',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '악력',       sub: 'kg',      value: 54.7, display: '54.7',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 41, armMs: 92,
      g1: 41, g2: 51,
      comment: '· 전 구간 이상 타이밍 범위 · 교과서적 시퀀스',
    },
    angular: {
      pelvis: 605, trunk: 805, arm: 1505,
      pelvisBand: 'mid', trunkBand: 'mid', armBand: 'mid',
      gainPT: 1.33, gainTA: 1.87,
      comment: '· 3개 분절 전부 기준 범위 · 밸런스 잡힌 회전 속도',
    },
    energy: {
      etiPT: 6.44, etiTA: 1.04, leakPct: 0,
      comment: '',
    },
    layback: { deg: 187.1, band: 'high', note: '· 프로 범위 180°+ 도달 · 가속 거리 충분' },
    strengths: [
      { title: '하체 단위파워 우수', detail: '· CMJ 단위파워 56.9 W/kg · 기준 상위' },
      { title: '반응·폭발성 (RSI) 우수', detail: '· CMJ RSI-mod 0.67 m/s · 기준 상위' },
      { title: '몸통→상완 에너지 전달 우수', detail: '· ETI 1.04 · 기준 상위' },
    ],
    weaknesses: [
      { title: '전 영역 기준 충족 · 약점 없음', detail: '· 현재 수준을 유지하며 절대 근력 보강 시 추가 상승 여력' },
    ],
    flags: [],
    training: [
      { cat: '근력', title: '근력 보강 (단위파워 유지)', weeks: '6–8주',
        rationale: '· 단위파워 이미 우수 · 절대 근력 증가 시 파워 총량 동반 상승',
        drills: ['Back squat 4×6 @ 75%', 'Trap-bar deadlift 3×5', 'Romanian deadlift 3×8'] },
    ],
  },
  {
    id: 'jeong',
    name: '정원진',
    nameEn: 'Jeong Won-jin',
    video: 'assets/jeong.mp4',
    velocity: 133.0,
    velocityAvg: 131.2,
    archetype: '파워 개발 필요형',
    archetypeEn: 'Power-deficit (strength untested)',
    tags: ['reactive-'],
    coreIssue: '몸통→상완 에너지 누수',
    coreIssueEn: 'Trunk → Arm energy transfer inefficiency',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      cmjPower: { cmj: 48.3, sj: 29.1, band: 'low' },
      maxStrength: { abs: null, perKg: null, band: 'na' },
      reactive: { cmj: 0.49, sj: 0.27, band: 'low' },
      ssc: { value: 1.09, band: 'mid' },
      release: { value: 50.0, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: 'CMJ 파워',   sub: 'W/kg',    value: 48.3, display: '48.3',  lo: 40, hi: 50 },
      { key: 'sj',    label: 'SJ 파워',    sub: 'W/kg',    value: 29.1, display: '29.1',  lo: 38, hi: 50 },
      { key: 'str',   label: '절대근력',   sub: 'N/kg',    value: null, display: 'N/A',   lo: 25, hi: 35 },
      { key: 'rsi',   label: '반응성',     sub: 'RSI-mod', value: 0.27, display: '0.27',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: 'EUR',        sub: 'SSC',     value: 1.09, display: '1.09',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '악력',       sub: 'kg',      value: 50.0, display: '50.0',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 42, armMs: 80,
      g1: 42, g2: 38,
      comment: '· 전 구간 이상 타이밍 범위 · 교과서적 시퀀스',
    },
    angular: {
      pelvis: 610, trunk: 835, arm: 1478,
      pelvisBand: 'mid', trunkBand: 'mid', armBand: 'mid',
      gainPT: 1.37, gainTA: 1.77,
      comment: '· 3개 분절 전부 기준 범위 · 밸런스 잡힌 회전 속도',
    },
    energy: {
      etiPT: 7.06, etiTA: 0.77, leakPct: 22,
      comment: '· 몸통→상완 에너지 손실 약 22% · lag 타이밍 부족 추정 · 흉추 가동성·분절 타이밍 점검 필요',
    },
    layback: { deg: 169.2, band: 'mid', note: '· 프로 범위 160°–180° 내' },
    strengths: [
      { title: '신장성 활용 (SSC) 정상', detail: '· EUR 1.09 · SSC 활용 정상 범위' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.77 · 기준 0.85 미만' },
      { title: '하체 단위파워 기준 미만', detail: '· SJ 단위파워 29.1 W/kg' },
      { title: '반응·폭발성 (RSI) 기준 미만', detail: '· SJ RSI-mod 0.27 m/s' },
    ],
    flags: [
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.77 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 확보 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 몸통 운동량 상완 전달 부족',
        drills: ['Connection ball drill', 'Lag drill · 타월/medicine ball', '흉추 회전·신전 mobility', 'Towel drill'] },
      { cat: '파워', title: '하체 파워 개발 우선', weeks: '6–8주',
        rationale: '· 하체 단위파워 기준 미만 (특히 SJ) · 메카닉과 별개로 파워 개발 필수',
        drills: ['Plyometric · box jump, broad jump 주 2회', 'Jump squat 4×3', 'Hang clean / Snatch technique', 'Lateral bound'] },
    ],
  },
  {
    id: 'kim',
    name: '김주원',
    nameEn: 'Kim Ju-won',
    video: 'assets/kim.mp4',
    velocity: 145.1,
    velocityAvg: 140.9,
    archetype: '근력 중심형',
    archetypeEn: 'Heavy / Strength-dominant',
    tags: ['reactive+', 'ssc-strong', 'release-capacity-high'],
    coreIssue: '몸통→상완 에너지 누수',
    coreIssueEn: 'Trunk → Arm energy transfer inefficiency',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      cmjPower: { cmj: 37.7, sj: 43.7, band: 'low' },
      maxStrength: { abs: 2525, perKg: 29.7, band: 'mid' },
      reactive: { cmj: 0.46, sj: 0.62, band: 'high' },
      ssc: { value: 1.18, band: 'high' },
      release: { value: 74.2, band: 'high' },
    },
    radar: [
      // axis, label, sub, value, low, high, displayValue
      { key: 'cmj',   label: 'CMJ 파워',   sub: 'W/kg',    value: 37.7, display: '37.7',  lo: 40, hi: 50 },
      { key: 'sj',    label: 'SJ 파워',    sub: 'W/kg',    value: 43.7, display: '43.7',  lo: 38, hi: 50 },
      { key: 'str',   label: '절대근력',   sub: 'N/kg',    value: 29.7, display: '29.7',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '반응성',     sub: 'RSI-mod', value: 0.46, display: '0.46',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: 'EUR',        sub: 'SSC',     value: 1.18, display: '1.18',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '악력',       sub: 'kg',      value: 74.2, display: '74.2',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 51, armMs: 111,
      g1: 51, g2: 59,
      comment: '· 골반→몸통 간격 느림 · 하체 회전 완성 前 몸통 개방 가능성',
    },
    angular: {
      pelvis: 569, trunk: 682, arm: 1383,
      pelvisBand: 'low', trunkBand: 'low', armBand: 'low',
      gainPT: 1.20, gainTA: 2.03,
      comment: '· 3개 분절 모두 기준 미만 · 분절별 가속 부족',
    },
    energy: {
      etiPT: 4.16, etiTA: 0.68, leakPct: 31,
      comment: '· 몸통→상완 에너지 손실 약 31% · lag 타이밍 부족 추정 · 흉추 가동성·분절 타이밍 점검 · 구속 상승 핵심 지렛대',
    },
    layback: { deg: 194.8, band: 'high', note: '· 프로 범위 180°+ 도달 · 가속 거리 충분' },
    strengths: [
      { title: '반응·폭발성 (RSI) 우수', detail: '· SJ RSI-mod 0.62 m/s · 기준 상위' },
      { title: '신장성 활용 (SSC) 우수', detail: '· EUR 1.18 · SSC 활용 강함 · CMJ·SJ 격차 큼' },
      { title: '악력 우수', detail: '· 악력 74.2 kg · 기준 상위 · 전완·손목 용량 충분' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.68 · 기준 0.85 미만' },
      { title: '하체 단위파워 기준 미만', detail: '· CMJ 단위파워 37.7 W/kg' },
    ],
    flags: [
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.68 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 확보 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 분절 타이밍·흉추 가동성 핵심 축',
        drills: ['Connection ball drill · 팔·몸통 분리 타이밍', 'Lag drill · 타월/medicine ball 팔 지연 감각', '흉추 회전·신전 mobility · foam roller, open book', 'Towel drill · 긴 팔 끌고 오기'] },
      { cat: '파워', title: '파워 변환 (근력→폭발력)', weeks: '6–8주',
        rationale: '· 절대 근력 양호 · 폭발적 발현력 부족 · 플라이오·탄성 비중 확대로 RSI 개선',
        drills: ['Power clean 4×3 @ 60–75% 1RM', 'Jump squat · 가벼운 barbell', 'Medicine ball rotational throw', 'Depth jump 3×5'] },
    ],
  },
  {
    id: 'kwon',
    name: '권준서',
    nameEn: 'Kwon Jun-seo',
    video: 'assets/kwon.mp4',
    velocity: 122.7,
    velocityAvg: 121.1,
    archetype: '탄력 중심형',
    archetypeEn: 'Lightweight / Elastic',
    tags: ['reactive+'],
    coreIssue: '· 엔진 총량 부족 · 몸통→상완 전달 저하',
    coreIssueEn: 'Low engine size + Trunk → Arm inefficiency',
    severity: 'HIGH',
    date: '2026-04-24',
    physical: {
      cmjPower: { cmj: 56.7, sj: 57.5, band: 'high' },
      maxStrength: { abs: 1765, perKg: 27.0, band: 'mid' },
      reactive: { cmj: 0.48, sj: 0.97, band: 'high' },
      ssc: { value: 1.10, band: 'mid' },
      release: { value: 49.1, band: 'mid' },
    },
    radar: [
      { key: 'cmj',   label: 'CMJ 파워',   sub: 'W/kg',    value: 56.7, display: '56.7',  lo: 40, hi: 50 },
      { key: 'sj',    label: 'SJ 파워',    sub: 'W/kg',    value: 57.5, display: '57.5',  lo: 38, hi: 50 },
      { key: 'str',   label: '절대근력',   sub: 'N/kg',    value: 27.0, display: '27.0',  lo: 25, hi: 35 },
      { key: 'rsi',   label: '반응성',     sub: 'RSI-mod', value: 0.97, display: '0.97',  lo: 0.3, hi: 0.55 },
      { key: 'eur',   label: 'EUR',        sub: 'SSC',     value: 1.10, display: '1.10',  lo: 0.95, hi: 1.10 },
      { key: 'grip',  label: '악력',       sub: 'kg',      value: 49.1, display: '49.1',  lo: 50, hi: 65 },
    ],
    sequence: {
      pelvisMs: 0, trunkMs: 31, armMs: 77,
      g1: 31, g2: 46,
      comment: '· 전 구간 이상 타이밍 범위 · 교과서적 시퀀스',
    },
    angular: {
      pelvis: 540, trunk: 929, arm: 1486,
      pelvisBand: 'low', trunkBand: 'high', armBand: 'mid',
      gainPT: 1.72, gainTA: 1.60,
      comment: '· 몸통 강점 · 골반 기준 미만 · 분절 간 가속 패턴 불균형',
    },
    energy: {
      etiPT: 6.44, etiTA: 0.60, leakPct: 39,
      comment: '· 몸통→상완 에너지 손실 약 39% · lag 타이밍 부족 추정 · 흉추 가동성·분절 타이밍 점검 필요',
    },
    layback: { deg: 186.3, band: 'high', note: '· 프로 범위 180°+ 도달 · 가속 거리 충분' },
    strengths: [
      { title: '하체 단위파워 우수', detail: '· CMJ 단위파워 56.7 W/kg · 기준 상위' },
      { title: '반응·폭발성 (RSI) 우수', detail: '· SJ RSI-mod 0.97 m/s · 기준 상위' },
      { title: '어깨 외회전 가동범위 우수', detail: '· Max Layback 186° · 기준 상위' },
    ],
    weaknesses: [
      { title: '몸통→상완 에너지 누수', detail: '· ETI trunk→arm 0.60 · 기준 0.85 미만' },
      { title: '엔진 총량 부족', detail: '· 단위파워 양호 · 절대 용량 작음 (1765 N / 65.4 kg)' },
    ],
    flags: [
      { severity: 'MEDIUM', title: '엔진 총량 부족 · 단위파워 양호 · 절대 용량 작음',
        evidence: ['절대 근력 추정치 1765 N (IMTP_F) · Low 범위', '체중 65.4 kg', 'CMJ 단위파워 56.7 W/kg · High'],
        implication: '· 탄력·반응성 양호 · 근력·체중 총량 작음 · 구속 천장 제한 · 중량 복합운동 중심 절대 근력·체중 증가 블록 우선' },
      { severity: 'HIGH', title: '몸통→상완 에너지 누수',
        evidence: ['ETI trunk→arm 0.60 · 기준 0.85 미만'],
        implication: '· 몸통→상완 전달 손실 · lag drill 필요 · 흉추 회전 가동성 · 분절 간 타이밍 재조정' },
    ],
    training: [
      { cat: '메카닉', title: '몸통→상완 에너지 전달 개선', weeks: '4–6주',
        rationale: '· ETI trunk→arm 기준(0.85) 미만 · 몸통 운동량 상완 전달 부족',
        drills: ['Connection ball drill', 'Lag drill · 타월/medicine ball', '흉추 회전·신전 mobility', 'Towel drill'] },
      { cat: '근력', title: '절대 근력·체중 증가 블록', weeks: '8–12주',
        rationale: '· 단위체중 파워 양호 · 절대 근력·체중 총량 작음 · 구속 천장 제한',
        drills: ['Back squat 4×5–8 @ 75–85% 1RM', 'Trap-bar deadlift 3×5', 'Bench press 4×5', '식사량·단백질 증가 · 0.25–0.5 kg/주 체중 증가 목표'] },
    ],
  },
];

// Professional reference ranges
window.BBL_REF = {
  pelvis:  { low: 580, high: 640 },
  trunk:   { low: 800, high: 900 },
  arm:     { low: 1450, high: 1600 },
  layback: { low: 160, high: 180 },
  etiTA:   { leakBelow: 0.85, ideal: 1.0 },
};
